insert into bairro(bai_id, bai_nome,bai_id_cidade) values (1,'  Adalberto Simão Nader ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (2,'  Aeroporto ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (3,'  Andana ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (4,'  Baía Nova ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (5,'  Barro Branco ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (6,'  Bela Vista ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (7,'  Belo Horizonte ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (8,'  Buenos Aires ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (9,'  Camurugi ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (10,'  Centro ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (11,'  Comunidade Urbana de Amarelos ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (12,'  Comunidade Urbana de Machinda ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (13,'  Condados ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (14,'  Coroado ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (15,'  Elza Nader ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (16,'  Enseada Azul ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (17,'  Iguape ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (18,'  Ilhas Verdes ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (19,'  Ipiranga ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (20,'  Itapebussu ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (21,'  Jabaraí ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (22,'  Jardim Boa Vista ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (23,'  Jardim Guarapari ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (24,'  Jardim Santa Rosa ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (25,'  Kubitschek ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (26,'  Lagoa Funda ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (27,'  Meaípe ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (28,'  Muquiçaba ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (29,'  Nossa Senhora da Conceição ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (30,'  Nossa Senhora de Fátima ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (31,'  Nova Guarapari ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (32,'  Olaria ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (33,'  Palmeiras ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (34,'  Parque Areia Preta ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (35,'  Paturá ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (36,'  Perocão ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (37,'  Pontal de Santa Mônica ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (38,'  Portal de Guarapari ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (39,'  Porto Grande ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (40,'  Praia do Morro ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (41,'  Praia do Riacho ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (42,'  Recanto da Sereia ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (43,'  Rio Calçado ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (44,'  Rio Grande ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (45,'  Samambaia ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (46,'  Santa Margarida ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (47,'  Santa Mônica ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (48,'  São Gabriel ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (49,'  São João do Jabuti ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (50,'  São José ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (51,'  São Judas Tadeu ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (52,'  Sol Nascente ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (53,'  Una ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (54,'  Várzea Nova ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (55,'  Vila Guaibura ',1599);
insert into bairro(bai_id, bai_nome,bai_id_cidade) values (56,'  Village do Sol ',1599);

