/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador.aula;

import gerenciador.conexaoBD.AulaDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wagner
 */
public class CadastroAulaGUI extends javax.swing.JFrame {
AulaDao conAula;
    public CadastroAulaGUI() {
        initComponents();
        conAula = new AulaDao();
        this.setLocation(500, 300);
        gerenciador.telas.ultilidades.FuncoesJanelas.setIncone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblMinimizar = new javax.swing.JLabel();
        edtValor = new javax.swing.JTextField();
        lblGravar = new javax.swing.JLabel();
        edtFechar = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtNome.setBorder(null);
        getContentPane().add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 49, 144, 20));

        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 8, 14, 10));

        edtValor.setBorder(null);
        getContentPane().add(edtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 76, 84, 21));

        lblGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGravarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGravarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGravarMouseExited(evt);
            }
        });
        getContentPane().add(lblGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 46, 73, 25));

        edtFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edtFecharMouseClicked(evt);
            }
        });
        getContentPane().add(edtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 8, 12, 10));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Telas Pequenas/tela aula.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 160));
        lblFundo.getAccessibleContext().setAccessibleName("lblFundo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edtFecharMouseClicked
       this.dispose();
    }//GEN-LAST:event_edtFecharMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
      this.setExtendedState(CadastroAulaGUI.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblGravarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGravarMouseEntered
       gerenciador.telas.ultilidades.Style.styleBorderEntered(lblGravar);
    }//GEN-LAST:event_lblGravarMouseEntered

    private void lblGravarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGravarMouseExited
        gerenciador.telas.ultilidades.Style.styleBorderExited(lblGravar);
    }//GEN-LAST:event_lblGravarMouseExited

    private void lblGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGravarMouseClicked
        if (!edtNome.getText().isEmpty() || !edtValor.getText().isEmpty()) {

            try {
        conAula.insertAula(edtNome.getText(),Double.parseDouble(edtValor.getText().replace(",", ".")));
    } catch (SQLException ex) {
        Logger.getLogger(CadastroAulaGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Estes campos são obrigatorios!");

        }
    }//GEN-LAST:event_lblGravarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAulaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAulaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAulaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAulaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAulaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edtFechar;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtValor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblGravar;
    private javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables
}
